### ISSUE TITLE
internal error in method "textDocument/documentSymbol" ...keeps popping up all the time

### ISSUE THREAD

**Issue by anentropic** [Eugleo/magic-racket#24] opened 2020-08-12 21:20 UTC
## Environment
- OS: MacOS
- OS Version: 10.14.6 Mojave
- VS Code Version: `1.47.3`
- Racket version: `7.7 3M`
- Racket Langserver checksum: `01bc4ad03e449dfbe1852a141748c3d6121a1e75`
- Magic Racket version: `0.5.6`

## Error message
```
Caught exn in request "textDocument/documentSymbol"
hash-ref: no value found for key
  key: 'file:///Users/anentropic/Documents/Dev/Personal/rkt-write-thru-hash/tests.rkt
  context...:
   /Users/anentropic/Library/Racket/7.7/pkgs/racket-langserver/text-document.rkt:242:0: document-symbol
   /Applications/Racket v7.7/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /Users/anentropic/Library/Racket/7.7/pkgs/racket-langserver/methods.rkt:26:0: process-message
   /Applications/Racket v7.7/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /Users/anentropic/Library/Racket/7.7/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 10:07:06 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
```
## Additional context
I was using Magic Racket pretty happily for a while.
Now it has started popping up this error every time I type something in my current file.
I don't think there is a syntax error in the file as it runs fine outside VS Code (and even if there was I would not want this intrusive error).
I have restarted VS Code but it's still happening.

---

If relevant, please enclose a minimal example file which triggers the errors. If you're unable to enclose the file, please do the following instead:

1. Enable logging in Magic Racket's settings. 
2. Restart VS Code.
3. Open the problematic file.
4. Trigger the error.
5. Copy the whole log from Output > Racket Language Server into some text file and enclose it to your bug report.

**Comment by anentropic** [comment] 2020-08-13 18:13
It's not a minimal example unfortunately, but this is the file which seems to be a problem:
https://github.com/anentropic/rkt-write-thru-hash/blob/e497eeea70221c85129c368a03a5dae04d6ae682/tests.rkt

**Comment by s0kil** [comment] 2020-08-27 03:28
Also getting this error:
```
Caught exn in request "textDocument/documentSymbol"
get-lexer: '(#<procedure:scribble-lexer> . #f)
  context...:
   /home/danielsokil/.racket/7.8/pkgs/racket-langserver/text-document.rkt:242:0: document-symbol
   /home/danielsokil/.asdf/installs/racket/7.8/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/danielsokil/.racket/7.8/pkgs/racket-langserver/methods.rkt:26:0: process-message
   /home/danielsokil/.asdf/installs/racket/7.8/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/danielsokil/.racket/7.8/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 11:27:56 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
```

**Comment by DanRowe1** [comment] 2020-09-02 23:21
Also getting this on Windows. Just started using Racket and downloaded this extension and as soon as I began typing in my hello_world.rkt file this error pops up on every keypress. Running VS Code 1.48.2

**Comment by Eugleo** [comment] 2020-09-17 18:37
Thanks for reporting, I'm very short on time at the moment, but I'll test it out ASAP.

**Comment by benrbray** [comment] 2020-09-30 20:46
I'm having the same issue.  I'm working through the [Beautiful Racket Stacker Tutorial](https://beautifulracket.com/stacker/the-reader.html) and even the most basic examples fail with the error above.

```
#! /home/ben/racket/bin/racket
#lang br/quicklang
42
```

```
[Error - 4:44:03 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
Caught exn in request "textDocument/documentSymbol"
get-lexer: 'before-lang-line
  context...:
   /home/ben/.racket/7.8/pkgs/racket-langserver/text-document.rkt:242:0: document-symbol
   /home/ben/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/ben/.racket/7.8/pkgs/racket-langserver/methods.rkt:26:0: process-message
   /home/ben/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/ben/.racket/7.8/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 4:44:04 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603

**Comment by Eugleo** [comment] 2020-10-01 04:43
@benrbray I _think_ your issue might be caused by not having the `#lang` on the first line in the file. Of course, that’s a bug, but it should be repoerted in the langserver repo instead. I’ll look into it and report it there if my guess is confirmed.

**Comment by benrbray** [comment] 2020-10-01 04:52
I just tested again with the first line omitted -- unfortunately I get the same error.  

Thanks for making this extension!  Looking forward to using it once I get past this issue.

**Comment by Eugleo** [comment] 2020-10-01 05:09
Thanks for checking! Then it will be some custom-lang induced error, I need to check (probably it'll still go to the langserver repo).

**Comment by silesky** [comment] 2020-11-12 15:15
@Eugleo I get the same error as @benrbray when doing the br tutorial, regardless of what line number the lang declaration is on.

**Comment by PPPatriccccc** [comment] 2020-12-01 18:25
I get the same error every time, and I found that some predicates are not in the suggested function. Btw I tried every language, advanced student, intermidiate, beginning, every one, it just doesn't work

**Comment by battleunicorn** [comment] 2021-03-30 19:00
I am experiencing the same issue described above. I am on windows if it helps.

**Comment by Runi-c** [comment] 2021-04-16 08:53
Every issue mentioned in this thread has been fixed over at the langserver in https://github.com/jeapostrophe/racket-langserver/pull/51, https://github.com/jeapostrophe/racket-langserver/pull/38, & https://github.com/jeapostrophe/racket-langserver/pull/53 (once it's merged)

Update your `racket-langserver`!

**Comment by Eugleo** [comment] 2021-04-16 09:03
Closing this issue. Reopen if the issue persists after updating once the PR is merged.

**Closed by Eugleo** 2021-04-16 09:03 UTC
Labels: bug
