### ISSUE TITLE
everything setup as instructed, nothing works in vscode, both racket and raco are installed from command line, path variable set

### ISSUE THREAD

**Issue by devil0947** [Eugleo/magic-racket#99] opened 2023-02-04 07:27 UTC
NOTHING in this "magic plugin" works

NOTHING

**Comment by Eugleo** [comment] 2023-02-04 08:46
You probably now this, but this kind of bug report is not of much use. If you wish to work with me to solve the issue, please add some information that could be used to debug this problem. A good starting point would be the REPORT A BUG template that you have probably accidentally overlooked:

```
- OS: [e.g. MacOS]
- OS Version [e.g. Catalina]
- VS Code Version [e.g. 1.46.1]
- Racket version [e.g. 7.7]
  - run: `racket -v`
- Racket Langserver checksum [e.g. 64c1827548089c97c56a53a90ef3d569deb0e6c2]
  - run: `raco pkg show --full-checksum racket-langserver`
- Magic Racket version [e.g. 0.5.6] 

# How can we reproduce the bug

# What is the expected behaviour
```

**Comment by Eugleo** [comment] 2023-02-04 09:17
Specifically, try running `racket -l racket-langserver` and report back.

**Comment by devil0947** [comment] 2023-02-05 02:54
first, thank you for your reply.
I apology for my tune, as i was trying to work this out for hours last night but in vain.

upon checking the command, "racket -l racket-langserver", 
it has no result, becuz it was hang on something, only flashing cursor waiting. 

i have all dependencies checked/ls installed/racket installed, everything is fine from command line, no errors.
raco knows my path, i ran 'raco pkg show --full-checksum racket-langserver' last night, here is the result, 

Installation-wide:
 [none]
User-specific for installation "8.6":
 Package            Checksum                                  Source
 racket-langserver  5f283eb8c4034ba9b0cb557dd616c0a1fe4d3fe8  catalog...erver.git

racket -v
Welcome to Racket v8.6 [cs].

as for the system i am using, it is latest ubuntu. 
i plan to move to emacs platform to use raket since i hate IDE in general.

thanks again for the reply

**Comment by Eugleo** [comment] 2023-02-05 08:17
These things can sometimes be frustrating. Thanks for the details! I don’t have time currently to investigate the issue, but will do it ASAP. If you’re moving to emacs then I am probably not in a hurry anyway :-) 5. 2. 2023 v 3:54, devil0947 ***@***.***>:﻿
first, thank you for your reply.
I apology for my tune, as i was trying to work this out for hours last night but in vain.
upon checking the command, "racket -l racket-langserver",
it has no result, becuz it was hang on something, only flashing cursor waiting.
i have all dependencies checked/ls installed/racket installed, everything is fine from command line, no errors.
raco knows my path, i ran 'raco pkg show --full-checksum racket-langserver' last night, here is the result,
Installation-wide:
[none]
User-specific for installation "8.6":
Package            Checksum                                  Source
racket-langserver  5f283eb8c4034ba9b0cb557dd616c0a1fe4d3fe8  catalog...erver.git
racket -v
Welcome to Racket v8.6 [cs].
as for the system i am using, it is latest ubuntu.
i plan to move to emacs platform to use raket since i hate IDE in general.
thanks again for the reply

**Comment by cocolato** [comment] 2023-02-24 05:50
Same problem, Is there a solution now？

**Comment by jryans** [comment] 2023-02-24 11:21
The extension is working just fine for me... I think we need to understand what the problem is before there can be a solution. It would appear there is something system-specific happening for each of you affected.

Please start by collecting the diagnostic info asked for above.

**Comment by cocolato** [comment] 2023-02-28 07:08
Thanks, I find it was a problem with my environment configuration, which has now been solved.

**Closed** 2023-02-28 07:09 UTC
Labels: bug
