### ISSUE TITLE
Automatic indentation and reindent

### ISSUE THREAD

**Issue by tautologico** [Eugleo/magic-racket#6] opened 2019-10-25 14:17 UTC
By default, DrRacket has automatic indentation, so that when pressing Enter the cursor starts the new line at a point determined by the auto indentation engine, instead of the same first column as the last line. Pressing tab on a line will also reindent the line according to the engine rules. This is related to but not the same as automatic formatting.

**Comment by Eugleo** [comment] 2019-10-25 15:55
I'm not sure this can be done in VS Code; there is a way to tell the code that it the new line indentation level should be +-1 relative to current line. Unfortunately, I don't think it's possible to customize it further than that.

**Comment by JJPro** [comment] 2020-04-07 07:47
I think we can close the issue, as this is duplicate of #9. 
The formatting/auto-indent feature reply on Racket LSP to work, but as stated in [racket-langserver](https://github.com/jeapostrophe/racket-langserver/blob/master/README.md#work-in-progress), the formatting feature is still WIP.

**Comment by Eugleo** [comment] 2020-04-08 07:52
I don't think they are the _same_ per se, just related. This issue is more about the behaviour when writing the code, while #9 is more about the formatting when you save the document. Bot are related, but separate problems.

**Comment by JJPro** [comment] 2020-04-08 08:03
> I don't think they are the _same_ per se, just related. This issue is more about the behaviour when writing the code, while #9 is more about the formatting when you save the document. Bot are related, but separate problems.

They are the same, to be more specific, it's called `onTypeFormatting` in [LSP specifications](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/). 
As per the LSP specification, there are three types of formatting capabilities: 
- **`textDocument/formatting`** I think this is whole document formatting
- **`textDocument/rangeFormatting`** to format selected range 
- **`textDocument/onTypeFormatting`**

**Comment by Eugleo** [comment] 2020-04-08 08:05
Oh wow, I learned something new today! I should really go through the LSP spec once.

**Comment by Eugleo** [comment] 2020-04-08 08:07
Closed as dupe of #9.

**Closed by Eugleo** 2020-04-08 08:07 UTC
Labels: enhancement
