### ISSUE TITLE
Load file into the current REPL error

### ISSUE THREAD

**Issue by ladesiji** [Eugleo/magic-racket#8] opened 2019-11-04 02:04 UTC
win 10 
when I click the button--"Load file into the current REPL"  ,  it doesn't work. the response :
```cmd
Welcome to Racket v7.3.
> (enter! (file "c:\User\ladesiji\example\2.2.rkt"))
; stdin:1:14: read-syntax: no hex digit following `\U` [,bt for context]
> ; serswangyuchenSICPexample2.2.rkt: undefined;
;  cannot reference an identifier before its definition
;   in module: top-level
; [,bt for context]
>
```
I fixed the path, not work too.
```cmd
(enter! (file "c:\\Users\\wangyuchen\\SICP\\example\\2.2.rkt"))
"))\r\n(enter! (file "
> ; |c:\Users\wangyuchen\SICP\example\2.2.rkt|: undefined;
;  cannot reference an identifier before its definition
;   in module: top-level
; [,bt for context]
>

```

**Comment by Eugleo** [comment] 2019-11-04 08:42
The second error message is weird, I would have guessed that fixing the escapes in the string would solve the issue... Could you please double check that you are entering the correct file in the correct way? I’d suggest:

1. Open a blank REPL in VS Code using the `Launch a new REPL` command
2. Manually enter the following code, with the backslashes in the path properly escaped.
```scheme
(enter! (file “path\\to\\file.rkt”))
```
3. Report the error (if it persists).

**Comment by massung** [comment] 2019-12-03 17:20
I'm also having this issue (Win 10). Windows can use `/` for file separator as well. I'd suggest changing this line to:

https://github.com/Eugleo/magic-racket/blob/master/src/extension.ts#L130

```js
terminal.sendText(`racket "${filePath.replace(/\\/g, '/')}"`);
```

**Comment by whitetigle** [comment] 2020-04-17 08:12
Same here. But your workaround works.

**Comment by Eugleo** [comment] 2020-04-27 10:58
@massung Thanks for the tip! I'll push your changes, could you please let me know if the issue is solved?

**Comment by Eugleo** [comment] 2020-04-27 11:00
Pushed b5ddcdbf7fa40ffda6c8cd953dd850c14ae1e05b to fix this issue.

**Comment by massung** [comment] 2020-04-27 13:03
Happy to. Is there an easy way for me to test the commit/latest without having to clone the repo, build, and install the extension myself locally (if it's updated in the Marketplace I haven't seen it)?

**Comment by Eugleo** [comment] 2020-04-27 13:23
I fear that’s the only way, but it should be relatively easy, along the lines of clone > npm install > press F5 to launch the extension. I didn’t push the new version to the marketplace, as it’s untested.

**Comment by massung** [comment] 2020-04-27 13:48
Okay. Got it. It's not completely fixed. The `run` command works fine, but `load` doesn't. Without going through all the steps of forking to make a PR, etc...

```
function normalizeFilePath(filePath: string) {
  if (process.platform == 'win32') {
    return filePath.replace(/\\/g, '/');
  }
  return filePath;
}

function loadFileInRepl(repl: vscode.Terminal, filePath: string) {
  repl.show();
  repl.sendText(`(enter! (file "${normalizeFilePath(filePath)}"))`);
}

// in runInTerminal
if (racket !== undefined) {
  terminal.sendText(`racket "${normalizeFilePath(filePath)}"`);
}
```

With these changes, it works fine on Windows. If it's easier and you'd like me to fork, make a PR, etc. I will. I'm also happy to just pull master again once you're ready for me to test it.

**Comment by Eugleo** [comment] 2020-04-27 13:56
Oh, of course, I got ahead of myself there. Fixed and commited — you can pull and test.

**Comment by massung** [comment] 2020-04-27 13:57
Looks good! Thanks!

**Comment by Eugleo** [comment] 2020-04-27 14:01
Great, thanks for the help! Closing #8.

**Closed by Eugleo** 2020-04-27 14:01 UTC
Labels: bug
