### ISSUE TITLE
"enter!: not a module path or #f" when Load file in REPL

### ISSUE THREAD

**Issue by NekoMonad** [Eugleo/magic-racket#115] opened 2023-07-02 14:07 UTC
## Environment
- OS: Windows 10
- OS Version: Win10.19045
- VS Code Version: 1.79.2
- Racket version: v8.7
- Racket Langserver checksum: fc37990ebaf77f0d606c10782e5012f73d663028
- Magic Racket version: 0.6.5

## Error message
code: `foo.rkt`
```racket
#lang scheme

(define (foo)
  (display "bar"))
```
terminal message:
```powershell
pwsh > racket --repl --eval '(enter! (file \"c:/Users/quantumbird/workspace/racket/foo.rkt\"))'
Welcome to Racket v8.7 [cs].
enter!: not a module path or #f
  at: (file |"c:/Users/quantumbird/workspace/racket/foo.rkt"|)
  in: (enter! (file |"c:/Users/quantumbird/workspace/racket/foo.rkt"|))
  context...:
   C:\Program Files\Racket\collects\racket\enter.rkt:10:0
> 
```

## Additional context
- PowerShell Version: 7.3.4

the REPL works normally when run `racket --repl --eval '(enter! (file "c:/Users/quantumbird/workspace/racket/foo.rkt"))'` in terminal

It looks like the plugin incorrectly identified my powershell version as pwsh 5, and added some reduntant slash into the command.

in `src/repl.ts`: `function createRepl`
```typescript
else if (isPowershellShell() && isVersion5Powershell()) {
      fullCommand += ` --eval '(enter! (file \\"${filePath}\\"))'`;
}
```
and `src/utils.ts`
```typescript
const isVersion5Powershell = (): boolean =>
  ["powershell.exe"].some((p) => vscode.env.shell.endsWith(p));
```

**Comment by jryans** [comment] 2023-07-04 10:32
Thanks for the report!

What is the PowerShell command you are using on your system? Is it `powershell` or `pwsh`?

Assuming the answer is `pwsh,` then my suspicion is this the same issue that was fixed by https://github.com/Eugleo/magic-racket/pull/110, but that's not in a released version yet, so that's presumably why it's not yet working.

**Comment by NekoMonad** [comment] 2023-07-04 17:12
Yes, in the vscode's REPL terminal, it is `C:\Program Files\PowerShell\7\pwsh.exe`
sorry to bother you, thanks for your reply and waiting for the new version :)

**Closed** 2023-07-04 17:13 UTC
Labels: bug

**Comment by jryans** [comment] 2023-07-04 17:32
No worries, glad to see we understand the cause. 🙂 

I'm hoping to release a new version in next few days or so.
