### ISSUE TITLE
Error when starting language server on Windows 10

### ISSUE THREAD

**Issue by cfinegan** [Eugleo/magic-racket#18] opened 2020-06-16 01:34 UTC
When attempting to open a Racket source file on Windows 10, VS Code produces the following error:

```
Couldn't start client Racket Language Client

A request has failed. See the output for more information.
Source: Magic Racket (Extension)
```

The output for `Racket Language Client` contains the following:

```
Launching server using command racket failed.
```

This is on:
Windows 10 Version 1903 (Build 18362.900)
VS Code version 1.46.0
Magic Racket version 0.5.6

`racket-langserver` is installed with the latest commit and is working correctly with other language clients on the same machine. 

Update: This issue appears not to occur under all circumstances. Steps to reliably reproduce:

1) Close any open instances of VS Code
2) Open VS Code by selecting the "New Window" option for VS Code in the Start menu
3) Open a folder or file containing Racket code

In my experience, the initialization is more likely to succeed when VS code automatically loads a Racket directory upon startup, and less likely to succeed when the user manually opens a Racket directory from a fresh window.

**Comment by Eugleo** [comment] 2020-08-07 09:42
Sorry for the delayed response, once I get access to a windows machine I’ll test this out. I’ll work on better error reporting in the meantime, as not to flood users with errors if something goes wrong.

**Comment by semerdzhiev** [comment] 2020-11-02 10:32
I was having a similar problem. It turned out that Racket was not added to the PATH environment variable (seems that the Racket installer does not do that). Once I did that, the extension started to work properly.

**Comment by PPPatriccccc** [comment] 2020-11-29 07:00
I am having the similar problem but on Mac, and I added racket to path, somehow it still doesn't work

**Comment by bitli** [comment] 2021-01-18 09:50
For what's it's worth. I had the same kind of problem when I specified the full path of Racket in the properties of the Magic Racket extension (as C:/Program files/Racket/racket).  Finally I added the Racket folder to the path in the system environment variable and juste specified racket as the executable (as it is by default), and this solved my problem.

**Comment by bevo009** [comment] 2021-02-06 11:04
I get the same error message upon first opening a .rkt file
I do have racket added to the path
Works fine on WSL2-Ubuntu 20.04, so I use that instead for now
```
OS: WIn10 and WSL2 Ubuntu 20.04
OS Version WIn10.0.19042 and WSL2 Ubuntu 20.04
VS Code Version [1.52.1]
Racket version [7.9 (win), 7.2 (wsl2)]
Magic Racket version [0.5.7]
```

**Comment by SchoofsKelvin** [comment] 2021-02-15 22:58
I could get it to work by adding `C:\Program Files\Racket` to my `PATH` _(and restarting VS Code in a way that it gets the updated environment)_ and adding `"magic-racket.general.racketPath": "Racket.exe"` to my `settings.json`. This is on Windows 10.

**Comment by dalev** [comment] 2021-09-01 13:55
I've been encountering this frequently.  I managed to find this stack trace by using VSCode's `Developer: Open Extension Logs Folder` command and opening the file `exthost.log`.  The error suggests perhaps some timing-related error?  Maybe a timeout, or perhaps a callback is not waiting for some initialization related promise to be fulfulled before executing?  

```
[2021-09-01 09:43:28.069] [exthost] [error] Error: Language client is not ready yet
	at LanguageClient.sendRequest (c:\Users\dalev\.vscode\extensions\evzen-wybitul.magic-racket-0.5.7\node_modules\vscode-languageclient\lib\client.js:1789:19)
	at provideHover (c:\Users\dalev\.vscode\extensions\evzen-wybitul.magic-racket-0.5.7\node_modules\vscode-languageclient\lib\client.js:884:35)
	at Object.provideHover (c:\Users\dalev\.vscode\extensions\evzen-wybitul.magic-racket-0.5.7\node_modules\vscode-languageclient\lib\client.js:892:23)
	at s.provideHover (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:164675)
	at c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:188830
	at We._withAdapter (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
	at We.$provideHover (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:188808)
	at h._doInvokeHandler (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at h._receiveOneMessage (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\dalev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Eugleo** [comment] 2021-12-26 09:18
I'm unable to reproduce this, probably it got fixed in 4accb9cb38961bb7316d91dcec36f3f439fa5a2e. Closing.

**Closed by Eugleo** 2021-12-26 09:18 UTC

**Comment by 1216892614** [comment] 2023-05-07 08:45
I still got this error with my WSL2 Ubuntu.
![image](https://user-images.githubusercontent.com/54391927/236667361-9aa6abe5-3ce2-4c30-9ef7-e67a03ccd80b.png)
And I do add this in my PATH.

**Comment by 1216892614** [comment] 2023-05-31 01:31
I fix this after I reinstall toolchain by bash feets.
Befor that I just Install it by my apt, witch install them in `bin` path. And vscode cannt execute them with root.

**Comment by eshXingXie** [comment] 2024-11-09 09:42
The same thing also happens in powershell terminal in vscode. 
Try to start vscode using adminstrator and everything will be alright.
OS: WIN11
I'm not sure if it may work on mac or linux.
